[package]
name = "areal-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
areal-runtime-protocol.workspace = true
areal-runtime-supervisor.workspace = true
areal-runtime-exec-native.workspace = true
clap.workspace = true
cordis-rs.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
async-trait.workspace = true
tempfile.workspace = true
uuid.workspace = true
